server:
  port: 8083

spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: plazoletatrace
  data:
    mongodb:
      uri: ${MONGODB_URI}

app:
  jwt:
    secret: ${JWT_SECRET}
